baseURL = "www.example.com"
languageCode = "en-us"
title = "Hugo Serif Theme"
theme = "hugo-serif-theme"

[params]
    google_analytics_id=""

[[menu.main]]
	name = "Home"
	url = "/"
    weight = 1

[[menu.main]]
	name = "What we do"
	url = "/services/"
    weight = 1

[[menu.main]]
    name = "Who we are"
    url = "/team/"
    weight = 2

[[menu.main]]
	name = "Testimonials"
	url = "/testimonials/"
	weight = 3

[[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 4